/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onyx_android_jni_NativeFileUtil */

#ifndef _Included_com_onyx_android_jni_NativeFileUtil
#define _Included_com_onyx_android_jni_NativeFileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onyx_android_jni_NativeFileUtil
 * Method:    getChangeTimestamp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_onyx_android_jni_NativeFileUtil_getChangeTimestamp
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
